name: aub_ai
description: AubAI brings you on-device gen-AI capabilities, including offline text generation and more, directly within your app.
version: 1.0.2
homepage: https://aub.ai
repository: https://github.com/BrutalCoding/aub.ai
issue_tracker: https://github.com/BrutalCoding/aub.ai/issues

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^10.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.1.5
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.3
  freezed: ^2.3.3
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true

funding:
 - https://github.com/sponsors/BrutalCoding
 - https://buymeacoffee.com/BrutalCoding

topics:
  - ai
  - llms
  - llamacpp
  - nlp
  - text-generation

